---
settings:
  name: ONTAP Cloud 9.3 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: 解決方案ONTAP
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  - name: 最新版Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-relnotes"
    version-number: ''
  - name: 其他版本
    url: cloud-volumes-ontap-relnotes/reference-other-versions.html
    version-number: ''
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 版本資訊首頁
    url: "/index.html"
  - title: 新增功能
    url: "/reference-new.html"
  - title: 支援的組態
    url: "/reference-supported-configs.html"
  - title: 儲存限制
    url: "/reference-storage-limits.html"
  - title: 已知問題
    url: "/reference-issues.html"
  - title: 已知限制
    url: "/reference-limitations.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 新增功能
      url: reference-new.html
  - title: 組態與限制
    links:
    - title: 支援的組態
      url: reference-supported-configs.html
    - title: 儲存限制
      url: reference-storage-limits.html
    - title: 限制
      url: reference-limitations.html
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central部落格
      url: https://cloud.netapp.com/blog
    - title: 雲端網路研討會
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有Cloud Manager文件
