---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 一般限制

下列限制適用於ONTAP AWS和Azure中的Cloud。



=== 最大並行複寫作業數

無論執行個體類型或機器類型為何、每個節點的並行SnapMirror或SnapVault 支援Cloud Volumes ONTAP 物件傳輸數量上限為100。



=== 軟體更新必須由Cloud Manager完成

必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。



=== 開機磁碟和根磁碟不支援加密

如果您已從雲端供應商啟用自動加密所有新磁碟區或磁碟的選項、則在部署ONTAP 該選項時、您必須暫時停用該選項。如果您不這麼做、ONTAP 那麼部署不成功的就會失敗。不支援將加密功能用於ONTAP 作業系統的開機磁碟和根磁碟。



=== 不得從雲端供應商的主控台修改雲端部署ONTAP

從ONTAP 雲端供應商的主控台變更支援的解決方案、會導致組態不受支援。Cloud Manager所建立及管理的任何對「支援雲端」資源所做的變更ONTAP 、都會影響系統穩定性及Cloud Manager管理系統的能力。



=== 磁碟和集合體必須從Cloud Manager進行管理

所有磁碟和集合體都必須直接從 Cloud Manager 建立和刪除。您不應從其他管理工具執行這些動作。這樣做可能會影響系統穩定性、阻礙未來新增磁碟的能力、並可能產生備援雲端供應商費用。



=== 不受授權限制SnapManager

支援每部伺服器的支援以不支援使用者為單位的使用許可。SnapManager ONTAP不SnapManager 支援每個儲存系統（不支援此套件）授權。



=== 不支援ONTAP 的支援功能

下列功能不支援ONTAP 搭配使用NetApp Cloud：

* Aggregate層級即時重複資料刪除技術
* Aggregate層級背景重複資料刪除技術
* 磁碟維護中心
* 磁碟資料抹除
* 光纖通道（FC）
* Flash資源池
* FlexCache
* 資料量FlexGroup
* 無限Volume
* 介面群組
* 內部網路模式LIF容錯移轉
* MetroCluster
* 多租戶（僅支援一個資料服務SVM）
* NetApp Volume Encryption
* RAID4、RAID-DP、RAID-TEC 功能（支援RAID0）
* 服務處理器
* SnapLock
* SnapMirror同步
* VLAN




== AWS中的已知功能限制ONTAP

下列已知限制會影響ONTAP AWS中的Cloud。



=== Amazon CloudWatch回報的誤報

由於Amazon CloudCloud在閒置時不會釋出CPU、因此Amazon CloudWatch可針對EC2執行個體回報高CPU警告、因為它能100%使用。ONTAP您可以忽略此警報。使用「flex統計 資料」命令可顯示CPU的實際使用量。ONTAP



=== 不支援立即儲存恢復的支援、不支援使用者使用Cloud HA配對ONTAP

節點重新開機後、合作夥伴必須先同步資料、才能退回儲存設備。重新同步資料所需的時間取決於節點當機時用戶端寫入的資料量、以及恢復期間的資料寫入速度。



=== AWS GovCloud（美國）區域的限制

* 如果您想要在Cloud Volumes ONTAP 任何AWS GovCloud（美國）區域中啟動執行個體、Cloud Manager必須部署在AWS GovCloud（美國）區域。
* AWS GovCloud（美國）地區不支援使用「隨用付費AMI」功能。ONTAP
* 當部署於AWS GovCloud（美國）區域時、Cloud Manager無法在ONTAP 適用於Microsoft Azure的NetApp私有儲存設備組態或適用於SoftLayer組態的NetApp私有儲存設備中探索到各種非功能性叢集。




=== 不支援中斷EBS磁碟區的連線與重新連線

不ONTAP 支援將EBS Volume從某個不支援的執行個體中分離出來、然後重新附加到另一個ONTAP 不支援的不支援的不支援。您應該使用Cloud Manager在執行個體之間複寫資料。



=== 加密限制

* 啟用ONTAP 了「支援不支援LUN移動」加密的系統不支援LUN移動。
* 即使是無法建立的集合體、亦可將加密金鑰傳送給金鑰管理程式。ONTAP
+
您必須從金鑰管理程式手動刪除金鑰。


